# Generated by Django 4.1.4 on 2022-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('native', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
            ],
        ),
    ]
